// SharedPreferences cache keys
const CACHED_VISITORS_SIGNIN_TIME = "CACHED_VISITORS_SIGNIN_TIME";

const CACHED_CHECKS_PAGE = "CACHED_CHECKS_PAGE";
const CACHED_VISITOR_LIST = "CACHED_VISITOR_LIST";
